apps/thread/urls.py
from django.urls import path
from . import views

app_name = 'threads'

urlpatterns = [
    path('', views.ThreadListView.as_view(), name='lists'),
    path('lists', views.ThreadListView.as_view(), name='lists'),
    path('show/<str:pk>', views.ThreadDetailView.as_view(), name='show'),
    path('create', views.ThreadCreateView.as_view(), name='create'),
    path('edit/<str:pk>', views.ThreadUpdateView.as_view(), name='edit'),
    path('delete/<str:pk>', views.ThreadDeleteView.as_view(), name='delete'),

    path('delete-sub/<str:pk>', views.SubThreadDeleteView.as_view(), name='delete-sub'),
    path('get-lists/<str:thread_id>', views.get_sub_threads, name='sub-thread-lists'), 

    path("list-threads/", views.list_threads, name="list-threads"),
    path("list-responses/", views.list_responses, name="list-responses"),
    path("detail-response/", views.detail_response, name="detail-response"),
    path("create-response", views.create_response, name="create-response"),
    path("edit-response/", views.edit_response, name="edit-response"),
    path("delete-response/", views.delete_response, name="delete-response"),
    
    path('links', views.ThreadLinkListView.as_view(), name='links'),
    path('current-links/', views.current_links, name='current-links'),
    path('link_thread2thread', views.link_thread2thread, name='link-thread2thread'),
    path('link_response2thread', views.link_response2thread, name='link-response2thread'),
    path('link_response2API', views.link_response2API, name='link-response2API'),

    path('delete-link/', views.delete_link, name='delete-link'),
    path('links/delete/<str:pk>', views.ThreadLinkDeleteView.as_view(), name='delete-link'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.whatsapp import views as whatsapp_views
from apps.thread import views, validation

from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('', include('apps.account.urls')),
    path("admin/", admin.site.urls),
    path('threads/', include('apps.thread.urls')),
    path('api/', include('apps.api.urls')),
    path('webhook/send-test-message', whatsapp_views.send_test_message),
    path('webhook/testing', whatsapp_views.testing),
    path('webhook/facebook', whatsapp_views.facebook),


    path('api/validation/date', validation.validate_date),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/app-with-nav.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | Disaster Digital Platform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Hotel Management System">
    <meta name="keywords" content="Hotel Management System">

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />

    {% include 'partials/css.html' %}
    {% block extra_css %}{% endblock %}

    <!--./Alpine JS -->
    <script defer src="https://unpkg.com/alpinejs@3.10.5/dist/cdn.min.js"></script>

    <!-- htmx -->
    <script src="https://unpkg.com/htmx.org@1.8.5"
        integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous">
        </script>
</head>

<body data-topbar="light">
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% include 'layouts/topbar.html'%}
        {% include 'layouts/sidebar.html'%}

        @include('layouts.topbar')
        @include('layouts.sidebar')
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content bg-light-grey">
            <div class="page-content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock content %}
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
            {% include 'layouts/footer.html' %}
        </div>
        <!-- end main content-->
    </div>
    <!-- END layout-wrapper -->

    {% include 'partials/js.html' %}

    {% block extra_js %}
    {% endblock extra_js %}
</body>

</html>

templates/layouts/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                Copyright 
                <script>
                    document.write(new Date().getFullYear())
                </script> © Prime Minister's Office (PMO). All right reserved.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Developed by <a href="#">Sacids Foundation for One Health.</a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/sidebar.html
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">
    <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <!-- <li class="menu-title text-white" key="t-menu">Sidebar</li> -->

                <!-- <li>
                    <a href="#" class="waves-effect">
                        <i class="bx bx-home text-white"></i>
                        <span key="t-dashboards">Dashboard</span>
                    </a>
                </li> -->

                <li>
                    <a href="{% url 'threads:lists' %}" class="waves-effect">
                        <i class='bx bx-message-square-dots text-primary'></i>
                        <span key="t-dashboards">Threads</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'threads:links' %}" class="waves-effect">
                        <i class='bx bx-link-alt text-primary'></i>
                        <span key="t-layouts">Linked Trees</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

templates/layouts/topbar.html
{% load static %}
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="#" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/CoatofArms_Lg.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/CoatofArms_Lg.png' %}" alt="" height="17">
                    </span>
                </a>

                <a href="#" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/CoatofArms_Lg.png' %}" alt="" height="12">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/CoatofArms_Lg.png' %}" alt="" height="32">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search here...">
                    <span class="bx bx-search-alt"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">
            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search here..."
                                    aria-label="Search input">
                                <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>s
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="d-none d-xl-inline-block ms-1" key="t-henry">
                        RN
                    </span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <span class="dropdown-item text-sm">
                        <a href="{% url 'change-password' %}">Change Password</a>
                    </span>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-sm text-danger" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
</header>