apps/thread/urls.py
from django.urls import path
from . import views

app_name = 'threads'

urlpatterns = [
    path('', views.ThreadListView.as_view(), name='lists'),
    path('lists', views.ThreadListView.as_view(), name='lists'),
    path('show/<str:pk>', views.ThreadDetailView.as_view(), name='show'),
    path('create', views.ThreadCreateView.as_view(), name='create'),
    path('edit/<str:pk>', views.ThreadUpdateView.as_view(), name='edit'),
    path('delete/<str:pk>', views.ThreadDeleteView.as_view(), name='delete'),

    path('delete-sub/<str:pk>', views.SubThreadDeleteView.as_view(), name='delete-sub'),
    path('get-lists/<str:thread_id>', views.get_sub_threads, name='sub-thread-lists'), 

    path("list-threads/", views.list_threads, name="list-threads"),
    path("list-responses/", views.list_responses, name="list-responses"),
    path("detail-response/", views.detail_response, name="detail-response"),
    path("create-response", views.create_response, name="create-response"),
    path("edit-response/", views.edit_response, name="edit-response"),
    path("delete-response/", views.delete_response, name="delete-response"),
    
    path('links', views.ThreadLinkListView.as_view(), name='links'),
    path('current-links/', views.current_links, name='current-links'),
    path('link_thread2thread', views.link_thread2thread, name='link-thread2thread'),
    path('link_response2thread', views.link_response2thread, name='link-response2thread'),
    path('link_response2API', views.link_response2API, name='link-response2API'),

    path('delete-link/', views.delete_link, name='delete-link'),
    path('links/delete/<str:pk>', views.ThreadLinkDeleteView.as_view(), name='delete-link'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.whatsapp import views as whatsapp_views
from apps.thread import views, validation

from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('', include('apps.account.urls')),
    path("admin/", admin.site.urls),
    path('threads/', include('apps.thread.urls')),
    path('api/', include('apps.api.urls')),
    path('webhook/send-test-message', whatsapp_views.send_test_message),
    path('webhook/testing', whatsapp_views.testing),
    path('webhook/facebook', whatsapp_views.facebook),


    path('api/validation/date', validation.validate_date),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/thread/forms.py
import datetime
from datetime import timedelta
from django import forms
from .models import *

class ThreadForm(forms.ModelForm):
    """
    A class to create form
    """
    def __init__(self, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        self.fields['message_type'].empty_label  = ('Select')
        self.fields['validation'].empty_label  = ('Select')
        self.fields['action'].empty_label  = ('Select')

    class Meta:
        model  = Thread
        exclude = ('created_by', 'updated_by', 'map_data')
        fields  = ('__all__')

        widgets = {
            'title': forms.Textarea(attrs={'class': '', 'id': 'title', 'placeholder': 'Write title in Swahili...', 'rows': 3 }),
            'title_en_us': forms.Textarea(attrs={'class': '', 'id': 'title_en', 'placeholder': 'Write title in English...', 'rows': 3 }),
            'block': forms.TextInput(attrs={'class': 'form-control', 'id': 'block', 'placeholder': 'Write thread block...', 'required': '' }),
            'db_flag': forms.TextInput(attrs={'class': 'form-control', 'id': 'flag', 'placeholder': 'Write flag...', 'required': '' }),
            'label': forms.TextInput(attrs={'class': 'form-control', 'id': 'label', 'placeholder': 'Write label...', 'required': '' }),
            'validation': forms.Select(attrs={'class': 'form-control', 'id': 'validation', 'placeholder': 'Write validation...', }),
            'validation_url': forms.TextInput(attrs={'class': 'form-control', 'id': 'validation_url', 'placeholder': 'Write validation API url...', }),
            'message_type': forms.Select(attrs={'class': 'form-control', 'id': 'message_type', 'placeholder': 'Write message type...', }),
            'action': forms.Select(attrs={'class': 'form-control', 'id': 'action', 'placeholder': 'action...' }),
            'action_url': forms.TextInput(attrs={'class': 'form-control', 'id': 'action', 'placeholder': 'Write action url...', }),
            'payload': forms.Textarea(attrs={'class': 'form-control', 'id': 'payload', 'placeholder': 'Write payload here...', 'rows': 2 }),
            'main_thread': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'main_thread'})
        } 

        labels = {
            'title': 'Title SW',
            'title_en_us': 'Title EN',
            'block': 'Block',
            'db_flag': 'Flag',
            'label': 'Label',
            'message_type': 'Message Type',
            'validation': 'Validation Rules',
            'validation_url': 'Validation API',
            'action': 'Action',
            'action_url': 'Action URL',
            'payload': 'Payload',
            'main_thread': 'Back Main Menu',
        }      

apps/thread/views.py
import json
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.http import JsonResponse
from .forms import ThreadForm
from .models import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages


class ThreadListView(generic.ListView):
    model = Thread
    context_object_name = 'threads'
    template_name = 'threads/lists.html'
    # paginate_by = 50

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadListView, self).dispatch( *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ThreadListView, self).get_context_data(**kwargs)
        context['title'] = "Threads"

        return context

    def get_queryset(self, *args, **kwargs):
        """Filter data"""
        threads = Thread.objects.order_by('block')

        return threads


class ThreadDetailView(generic.DetailView):
    """View details"""
    model = Thread
    context_object_name = 'thread'
    template_name = 'threads/show.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadDetailView, self).dispatch( *args, **kwargs) 

    def get_context_data(self, *args, **kwargs):
        context = super(ThreadDetailView, self).get_context_data(**kwargs)
        context['title'] = "Thread"

        sub_threads = SubThread.objects.filter(thread_id=self.kwargs['pk']).order_by('view_id')
        context['sub_threads'] = sub_threads
        return context


def list_threads(request):
    """Lists threads"""
    uuid = request.GET.get("uuid")

    """threads"""
    threads = Thread.objects.order_by('block')

    arr_data = []
    for val in threads:
        data = {
            'id': val.id,
            'title': val.title,
            'label': val.label,
            'message_type': val.message_type
        }
        arr_data.append(data)

    """response"""
    return JsonResponse(arr_data, safe=False)

def list_responses(request):
    """Lists responses"""
    uuid = request.GET.get("uuid")

    """responses"""
    responses = SubThread.objects.filter(thread_id=uuid).order_by('view_id')

    arr_data = []
    for val in responses:
        data = {
            'id': val.id,
            'view_id': val.view_id,
            'title': val.title,
        }
        arr_data.append(data)

    """response"""
    return JsonResponse(arr_data, safe=False)


def edit_response(request):
    """ response details"""
    uuid = request.GET.get("uuid")

    """response"""
    response = SubThread.objects.filter(pk=uuid).first()

    arr_data = {
        'id': response.id,
        'view_id': response.view_id,
        'title': response.title,
        'title_en': response.title_en_us
    }

    """response"""
    return JsonResponse(arr_data, safe=False)


def detail_response(request):
    """ response details"""
    uuid = request.GET.get("uuid")

    #response
    thread = Thread.objects.filter(pk=uuid).first()

    #render view
    return render(request, 'threads/linking.html', {'thread': thread})   


def create_response(request):
    """create new response"""
    if request.method == 'POST':
        post_data = json.loads(request.body)
        action = post_data['action']

        message = ""
        if action == 'create':
            new_sub                   = SubThread()
            new_sub.title             = post_data['title']
            new_sub.title_en_us       = post_data['title_en']
            new_sub.view_id           = post_data['view_id']
            new_sub.thread_id         = post_data["thread_id"]
            new_sub.save()

            #response message
            message = "Response created"

        elif action == 'edit':
            response_id = post_data['response_id']
            sub_thread  = SubThread.objects.get(pk=response_id)
            sub_thread.title             = post_data['title']
            sub_thread.title_en_us       = post_data['title_en']
            sub_thread.view_id           = post_data['view_id']
            sub_thread.save()

            #response message
            message = "Response updated"
        
        """return response"""
        return JsonResponse({"error": False, "success_msg": message} , safe=False)


def delete_response(request):
    """delete response"""
    uuid = request.GET.get("uuid")

    #response
    response = SubThread.objects.filter(pk=uuid)

    if response.count() > 0:
        response.delete()

        #delete linking if available
        ThreadLink.objects.filter(sub_thread_id=uuid).delete()

    """response"""
    return JsonResponse({"error": False, "success_msg": "Response deleted"}, safe=False)   


class ThreadCreateView(generic.CreateView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadCreateView, self).dispatch( *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = {'form': ThreadForm()}
        return render(request, 'threads/create.html', context)

    def post(self, request, *args, **kwargs):
        form = ThreadForm(request.POST)
        if form.is_valid():
            dt_menu = form.save(commit=False)
            dt_menu.created_by = request.user
            dt_menu.save()

            messages.success(request, 'Thread created')
            return HttpResponseRedirect(reverse_lazy('threads:lists'))
        return render(request, 'threads/create.html', {'form': form})  


class ThreadUpdateView(generic.UpdateView):
    """View to update"""
    model = Thread
    context_object_name = 'thread'
    form_class = ThreadForm
    template_name = 'threads/edit.html'

    def form_valid(self, form):
        dt_menu = form.save(commit=False)
        dt_menu.updated_by = self.request.user
        dt_menu.save()

        messages.success(self.request, 'Thread updated')
        return HttpResponseRedirect(reverse_lazy('threads:lists')) 


class ThreadDeleteView(generic.DeleteView):
    """View to delete a """ 
    model = Thread
    template_name = "threads/confirm_delete.html"

    def get_success_url(self):
        messages.success(self.request, "Thread deleted")
        return reverse_lazy('threads:lists') 


class SubThreadDeleteView(generic.DeleteView):
    """View to delete a sub thread""" 
    model = SubThread
    template_name = "threads/confirm_delete.html"

    def get_success_url(self, ):
        messages.success(self.request, "Sub thread deleted")
        return reverse_lazy('threads:lists') 



class ThreadLinkListView(generic.ListView):
    """Thread Links Crud Operation"""
    model = ThreadLink
    context_object_name = 'thread_links'
    template_name = 'thread_links/lists.html'
    # paginate_by = 50

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadLinkListView, self).dispatch( *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(ThreadLinkListView, self).get_context_data(**kwargs)
        context['title'] = "Thread Links"
        context['threads'] = Thread.objects.order_by('block')

        thread_links = ThreadLink.objects.order_by("thread__block").all()
        context['thread_links'] = thread_links

        return context

    def post(self, request):
        """create/updating thread link data"""
        thread_id = request.POST.get('thread_id')
        link_id = request.POST.get('link_id')

        sub_thread_id = None
        if request.POST.get('sub_thread_id') != '':
            sub_thread_id = request.POST.get('sub_thread_id')

        """update or create menu link"""
        thread_link, created = ThreadLink.objects.update_or_create(
            thread_id=thread_id, sub_thread_id=sub_thread_id, 
            defaults={"link_id" : link_id})
        
        #message
        messages.success(request, 'Thread tree created/update!')

        #redirect
        return HttpResponseRedirect(reverse_lazy('threads:links'))


def current_links(request):
    """Current Links"""
    uuid = request.GET.get("uuid")

    thread_links = ThreadLink.objects.filter(thread_id=uuid).order_by('sub_thread__view_id')


    arr_data = []
    for val in thread_links:
        if val.linking_type == 'THREAD_THREAD' or val.linking_type == 'RESPONSE_THREAD':
            title = val.link.title
        elif val.linking_type == 'RESPONSE_API':
            title = val.api_url    

        #create set
        data = {
            'id': val.id,
            'view_id': val.sub_thread.view_id if val.sub_thread else "A",
            'customer_type': val.customer_type,
            'title': val.sub_thread.title if val.sub_thread else "Any Text",
            'link': f"{title}",
        }
        arr_data.append(data)

    """response"""
    return JsonResponse(arr_data, safe=False)


def link_thread2thread(request):
    """Linking Thread 2 Thread"""  
    if request.method == 'POST':
        post_data = json.loads(request.body)
        thread_id = post_data['thread_id'] 
        customer_type = post_data['customer_type'] 
        link_id = post_data['link_id']  

        """update or create menu link"""
        thread_link, created = ThreadLink.objects.update_or_create(
            thread_id=thread_id, customer_type=customer_type,
            defaults={"link_id": link_id, "linking_type": "THREAD_THREAD"})

    """response"""
    return JsonResponse({"error": False, "success_msg": "Thread 2 Thread linked"}, safe=False) 


def link_response2thread(request):
    """Linking Response 2 Thread"""  
    if request.method == 'POST':
        post_data = json.loads(request.body)
        thread_id = post_data['thread_id']  
        response_id = post_data['response_id'] 
        customer_type = post_data['customer_type']
        link_id = post_data['link_id']  

apps/thread/templates/thread_links/confirm_delete.html
{% extends 'layouts/app-with-nav.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_field %}
{% load crispy_forms_tags %}
{% block title %} Threads {% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Thread Tree</h4>

            <div class="page-title-right">
                Delete Tree
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <form method="post">{% csrf_token %}
                    <p class="mb-3">Are you sure you want to delete "{{ object }}"?</p>
                    <input type="submit" value="Confirm" 
                    class="btn btn-outline-danger text-medium" />
                </form>

            </div>
        </div>
    </div>
</div>
<!-- end row -->

<!-- <div class="row">
    <div class="col-12">
        <div class="text-center my-3">
            <a href="javascript:void(0);" class="text-success"><i class="bx bx-loader bx-spin font-size-18 align-middle me-2"></i> Load more </a>
        </div>
    </div> 
</div> -->
<!-- end row -->

{% endblock %}

apps/thread/templates/thread_links/lists.html
{% extends 'layouts/app-with-nav.html' %}
{% load static %}
{% load humanize %}
{% block title %} Threads {% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Linked Trees</h4>

            <div class="page-title-right">
                <!-- <a href="{% url 'threads:create' %}" class="btn btn-outline-primary btn-sm">
                    New Thread
                </a> -->
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="">
            <div class="table-responsive">
                <table class="table project-list-table table-nowrap align-middle table-borderless">
                    <thead>
                        <tr>
                            <th scope="col" style="width: 50px">#</th>
                            <th scope="col">Thread</th>
                            <th scope="col" style="width: 40px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for val in thread_links %}
                        <tr>
                            <td><i class='bx bx-message-square-dots font-size-24 text-success'></i></td>
                            <td>
                                {{ val.thread.title }}<br />
                                <span class="font-weight-600">{{ val.sub_thread.title|default:"Any Text" }}</span> 
                                <i class='bx bx-right-arrow-alt'></i>
                                {{ val.link.title }}
                            </td>

                            <td>
                                <div class="dropdown">
                                    <a href="#" class="dropdown-toggle card-drop" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class="mdi mdi-dots-horizontal font-size-18"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-end">
                                        <a class="dropdown-item"
                                            href="{% url 'threads:delete-link' val.id %}">Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- end row -->

<!-- <div class="row">
    <div class="col-12">
        <div class="text-center my-3">
            <a href="javascript:void(0);" class="text-success"><i class="bx bx-loader bx-spin font-size-18 align-middle me-2"></i> Load more </a>
        </div>
    </div> 
</div> -->
<!-- end row -->

{% endblock %}

{% block extra_js %}

<script>
    $(document).ready(function () {
        $('#thread_id').on('change', function (e) {
            thread_id = $(this).val();
            baseURL = window.location.origin;

            $.ajax({
                url: baseURL + '/threads/get-lists/' + thread_id,
                type: "get",
                success: function (data) {
                    $('#sub_thread_id').html(data);
                }
            });
        });
    });
</script>

{% endblock extra_js %}